import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import Image from "next/image";
import deved from "../public/dev-ed-wave.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Sannufi Ivan Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900 ease-in duration-300">
        <section className=" min-h-screen">
          <nav className=" py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons dark:text-white ease-in duration-300">
              developedbyis
            </h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl dark:text-white"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-emerald-700 to-green-600 text-white px-5 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className=" text-5xl py-2  !text-transparent bg-gradient-to-r from-emerald-500 via-teal-500 to-cyan-500 bg-clip-text font-medium md:text-6xl">
              Sannufi Ivan
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl ease-in-out duration-300">
              Frontend developer and gamer.
            </h3>
            <p className=" text-medium py-5 leading-8 text-gray-700 dark:text-gray-400 md:text-xl max-w-xl mx-auto ease-in duration-300">
              Я очень люблю играть в доту. Но в лол больше и когда я играю у
              меня немного встают{" "}
              <span className="!text-transparent bg-gradient-to-r from-emerald-600 via-teal-600 to-cyan-600 bg-clip-text">
                {" "}
                сосочки.
              </span>{" "}
              Дарья тащит на сапе в соло катки ,я лишь иногда помогаю ультой. Я
              улитка.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-emerald-700 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image src={deved} layout="fill" objectFit="cover" />
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl pt-6 dark:text-white">Services I offer</h3>
            <p className="text-md pt-3 pb-8 leading-8 text-gray-700 dark:text-gray-400 md:text-xl max-w-xl mx-0">
              Конечно сервис громко сказано,но если позовете поиграть в{" "}
              <span className=" text-emerald-500">Валорант</span>
              ,то я буду за. <span className=" text-emerald-500">Валорант</span>
              классная игра ,но когда Даша дома ,мы играем в
              <span className=" text-emerald-500"> Lol</span>.Поэтому идите все
              нахуй бляя.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className=" text-center shadow-lg p-10 rounded-xl my-10 ">
              <Image
                src={design}
                width={100}
                height={100}
                className=" block ml-auto mr-auto"
              />
              <h3 className=" text-xl font-medium pt-8 pb-2 dark:text-white">
                Beatiful Designs
              </h3>
              <p className="py-2 dark:text-gray-400">
                Создаю неповторимые дизайны от которых ебало улетает на другую
                орбиту.
              </p>
              <h4 className="py-4 text-emerald-700 text-lg !text-transparent bg-gradient-to-r from-emerald-500 via-teal-500 to-cyan-500 bg-clip-text">
                Design tools I use
              </h4>
              <p className=" text-gray-800 py-1 dark:text-white">Photoshop</p>
              <p className=" text-gray-800 py-1 dark:text-white">Figma</p>
              <p className=" text-gray-800 py-1 dark:text-white">Illustrator</p>
            </div>
            <div className=" text-center shadow-lg p-10 rounded-xl my-10 ">
              <Image
                src={code}
                width={100}
                height={100}
                className=" block ml-auto mr-auto"
              />
              <h3 className=" text-xl font-medium pt-8 pb-2 dark:text-white">
                Beatiful Designs
              </h3>
              <p className="py-2 dark:text-gray-400">
                Создаю неповторимые дизайны от которых ебало улетает на другую
                орбиту.
              </p>
              <h4 className="py-4 text-emerald-700 text-lg !text-transparent bg-gradient-to-r from-emerald-500 via-teal-500 to-cyan-500 bg-clip-text">
                Design tools I use
              </h4>
              <p className=" text-gray-800 py-1 dark:text-white">Photoshop</p>
              <p className=" text-gray-800 py-1 dark:text-white">Figma</p>
              <p className=" text-gray-800 py-1 dark:text-white">Illustrator</p>
            </div>
            <div className=" text-center shadow-lg p-10 rounded-xl my-10 ">
              <Image
                src={consulting}
                width={100}
                height={100}
                className=" block ml-auto mr-auto"
              />
              <h3 className=" text-xl font-medium pt-8 pb-2 dark:text-white">
                Beatiful Designs
              </h3>
              <p className="py-2 dark:text-gray-400">
                Создаю неповторимые дизайны от которых ебало улетает на другую
                орбиту.
              </p>
              <h4 className="py-4 text-emerald-700 text-lg !text-transparent bg-gradient-to-r from-emerald-500 via-teal-500 to-cyan-500 bg-clip-text">
                Design tools I use
              </h4>
              <p className=" text-gray-800 py-1 dark:text-white">Photoshop</p>
              <p className=" text-gray-800 py-1 dark:text-white">Figma</p>
              <p className=" text-gray-800 py-1 dark:text-white">Illustrator</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className=" text-3xl py-1 dark:text-white">Portofolio</h3>
            <p className="text-md pt-6 pb-4 leading-8 text-gray-700 dark:text-gray-400 md:text-xl max-w-xl mx-0">
              Конечно сервис громко сказано,но если позовете поиграть в валорант
              ,то я буду за. <span className=" text-emerald-500">Валорант</span>{" "}
              классная игра ,но когда Даша дома ,мы играем в{" "}
              <span className=" text-emerald-500">Lol</span>.Поэтому идите все
              нахуй бляя.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image
                src={web1}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web2}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web3}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web4}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web5}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web6}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
